version: "3.8"

services:
  tests:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pytest-selenium-e2e
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    tty: true